const booksData = [
  {
    id: 1,
    month: 'July',
    buyNow: '',
    bookName: 'ASSISTANT TO THE VILLAIN',
    bookAuthor: 'Hannah Nicole Maehrer',
    bookBlurb: 'Comically Fun Adventure - No Spice',
    bookCoverImage:
      'https://images.squarespace-cdn.com/content/v1/66ca041b9b6e9f1983653134/66f5f823-0370-4e87-872b-b506dbfb7bb5/assistant+to+the+Villain.jpeg?format=2500w',
  },
  {
    id: 2,
    month: 'July',
    buyNow: '',
    bookName: 'BLOOD OATH',
    bookAuthor: 'Morgan B Lee',
    bookBlurb: 'A SPICY Reverse Harem Series',
    bookCoverImage:
      'https://images.squarespace-cdn.com/content/v1/66ca041b9b6e9f1983653134/7bf78baa-5879-4094-8434-b8b1f1ad1d5b/Blood+Oath.jpg?format=2500w',
  },
  {
    id: 3,
    month: 'July',
    buyNow: '',
    bookName: 'GRUMPY ROMANCE',
    bookAuthor: 'Nia Arthurs',
    bookBlurb: 'Billionare Dad Romance',
    bookCoverImage:
      'https://images.squarespace-cdn.com/content/v1/66ca041b9b6e9f1983653134/cfebf497-3a56-4ff6-91be-28f5f227907f/Grumpy+Romance.jpg?format=2500w',
  },
  {
    id: 4,
    month: 'July',
    buyNow: '',
    bookName: 'SERPENT & DOVE',
    bookAuthor: 'Shelby Mahurin',
    bookBlurb: 'First of the Trilogy!',
    bookCoverImage:
      'https://images.squarespace-cdn.com/content/v1/66ca041b9b6e9f1983653134/e274b6fc-b193-4296-9a3a-653222f88c61/Serpent+and+Dove.jpg?format=2500w',
  },
  {
    id: 5,
    month: 'May',
    buyNow: '',
    bookName: 'PHANTASMA',
    bookAuthor: 'Kaylie Smith',
    bookBlurb: '',
    bookCoverImage: '/book-covers/May/book1.jpg',
  },
  {
    id: 6,
    month: 'May',
    buyNow: '',
    bookName: 'DAUGHTER OF THE MOON GOODESS',
    bookAuthor: 'Sue Lynn Tan',
    bookBlurb: '',
    bookCoverImage: '/book-covers/May/book2.jpg',
  },
  {
    id: 7,
    month: 'May',
    buyNow: '',
    bookName: 'FROM BLOOD AND ASH',
    bookAuthor: 'Jennifer Armentrout',
    bookBlurb: '',
    bookCoverImage: '/book-covers/May/book3.jpg',
  },
  {
    id: 8,
    month: 'May',
    buyNow: '',
    bookName: 'BREAK THE GIRL',
    bookAuthor: 'Rachel Jonas & Nikki Thorne',
    bookBlurb: '',
    bookCoverImage: '/book-covers/May/book4.jpg',
  },
  {
    id: 9,
    month: 'April',
    buyNow: '',
    bookName: "THE ASSASSIN'S BLADE",
    bookAuthor: 'Sarah J Maas',
    bookBlurb: 'No-Low Spice',
    bookCoverImage: '/book-covers/April/book1.jpg',
  },
  {
    id: 10,
    month: 'April',
    buyNow: '',
    bookName: 'THE ASHES AND THE STAR CURSED KING',
    bookAuthor: 'Carissa Broadbent',
    bookBlurb: 'Medium Spice',
    bookCoverImage: '/book-covers/April/book2.jpg',
  },
  {
    id: 11,
    month: 'April',
    buyNow: '',
    bookName: 'THE COVEN',
    bookAuthor: 'Harper L Woods',
    bookBlurb: 'High Spice',
    bookCoverImage: '/book-covers/April/book3.jpg',
  },
  {
    id: 12,
    month: 'April',
    buyNow: '',
    bookName: 'TRIAL OF THE SUN',
    bookAuthor: 'Nisha J Tuli',
    bookBlurb: 'Low-Medium Spice',
    bookCoverImage: '/book-covers/April/book4.jpg',
  },
  {
    id: 13,
    month: 'March',
    buyNow: '',
    bookName: 'A CURSE SO DARK AND LONELY',
    bookAuthor: 'Brigid Kemmerer',
    bookBlurb: 'No-Low Spice',
    bookCoverImage: '/book-covers/March/book1.jpg',
  },
  {
    id: 14,
    month: 'March',
    buyNow: '',
    bookName: 'THE SERPENT AND THE WINDS OF NIGHT',
    bookAuthor: 'Carissa Broadbent',
    bookBlurb: 'Medium Spice',
    bookCoverImage: '/book-covers/March/book2.jpg',
  },
  {
    id: 15,
    month: 'March',
    buyNow: '',
    bookName: 'KINGDOM OF THE WICKED',
    bookAuthor: 'Kerri Maniscalco',
    bookBlurb: 'High Spice',
    bookCoverImage: '/book-covers/March/book3.jpg',
  },
  {
    id: 16,
    month: 'March',
    buyNow: '',
    bookName: 'THE KING OF FROST AND SHADOWS',
    bookAuthor: 'Jen L. Grey',
    bookBlurb: 'Medium Spice',
    bookCoverImage: '/book-covers/March/book4.jpg',
  },
];

export default booksData;
